import Anthropic from "@anthropic-ai/sdk";
import { NextResponse } from "next/server";
import { buildBrandPrompt, brandContext } from "@/lib/brand-context";
import { buildDesignSystemPrompt } from "@/lib/design-system";

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

export async function POST(request) {
  try {
    const { description, adWidth, adHeight, flavor, channel } =
      await request.json();

    if (!description) {
      return NextResponse.json(
        { error: "No description provided" },
        { status: 400 }
      );
    }

    const brandColorsList = [];
    if (brandContext.colors?.primary) {
      Object.entries(brandContext.colors.primary).forEach(([name, hex]) => {
        brandColorsList.push(`${name}: ${hex}`);
      });
    }
    if (brandContext.colors?.pairings) {
      Object.entries(brandContext.colors.pairings).forEach(([name, hex]) => {
        brandColorsList.push(`${name}: ${hex}`);
      });
    }

    const product = brandContext.products?.find((p) => p.flavor === flavor);

    const prompt = `You are a senior creative director at a top advertising agency, designing an ad for ChiChi Foods.

BRAND CONTEXT:
${buildBrandPrompt()}

AVAILABLE BRAND COLORS (use ONLY these): ${brandColorsList.join(", ")}

${buildDesignSystemPrompt()}

YOUR TASK:
Design a stunning, scroll-stopping ${adWidth}x${adHeight}px ad for ChiChi Foods based on this brief:
"${description}"

CREATIVE RULES:
1. Be INVENTIVE with the layout. Use grids, bold typography, creative compositions, geometric shapes, color blocks, overlapping elements, diagonal sections. The ad must look like it was made by a human designer, not generated by AI.
2. USE ONLY the ChiChi brand colors listed above. Create a vibrant, eye-catching palette from these.
3. The root <div> must be EXACTLY ${adWidth}px wide and ${adHeight}px tall with overflow:hidden and position:relative.
4. ALL styling must be inline. No <style> tags, no CSS classes.
5. Use {{token_name}} placeholders for ALL text content.
6. Only include <img> tags if the user specifically mentioned images/photos and provided URLs.
7. Write punchy, on-brand copy. Lead with taste and experience, then nutrition facts. ChiChi makes CHICKPEA protein hot cereal, NOT oatmeal.
8. Think about what would make someone STOP SCROLLING on Instagram. The ad should demand attention in the first 0.5 seconds.
${product ? `\nFEATURED PRODUCT: ${product.name} — ${product.keyBenefit} (${product.protein} protein, ${product.calories} cal)` : ""}
${channel ? `\nCHANNEL: ${channel} — optimize the design for this platform.` : ""}

Return ONLY valid JSON (no markdown fences, no explanation):
{
  "design_rationale": {
    "aesthetic": "description of visual style",
    "layout_technique": "what makes layout interesting",
    "color_strategy": "which brand colors and how",
    "polish_techniques": ["technique1", "technique2", "technique3"]
  },
  "html": "<div style='width:${adWidth}px;height:${adHeight}px;position:relative;overflow:hidden;...'>...{{token}} placeholders...</div>",
  "fields": {
    "token_name": "actual text value"
  },
  "backgroundColor": "#hex",
  "textColor": "#hex",
  "accentColor": "#hex"
}`;

    const response = await client.messages.create({
      model: "claude-sonnet-4-20250514",
      max_tokens: 6000,
      messages: [
        {
          role: "user",
          content: prompt,
        },
      ],
    });

    const text = response.content[0].text;
    let result;
    try {
      result = JSON.parse(text);
    } catch {
      const jsonMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/);
      if (jsonMatch) {
        result = JSON.parse(jsonMatch[1].trim());
      } else {
        const objMatch = text.match(/\{[\s\S]*\}/);
        if (objMatch) {
          result = JSON.parse(objMatch[0]);
        } else {
          throw new Error("Could not parse AI response");
        }
      }
    }

    if (!result.html || !result.fields) {
      throw new Error("AI response missing html or fields");
    }

    return NextResponse.json(result);
  } catch (error) {
    console.error("Generate ad error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to generate ad" },
      { status: 500 }
    );
  }
}
